src/components/common/Header/index.jsx
src/components/index.js
src/pages/_document.jsx

- [Feat | Header 컴포넌트 제작](https://github.com/beomgye/where-is-my-hometown/commit/6d33fb98935500a8d01c0b0d5db2e839081dd8a8)

Feat | Header 컴포넌트 제작

---

src/components/AssetInputForm/index.js
src/components/BuildingTypeForm/index.js
src/components/FinishForm/index.js
src/components/LocationForm/index.js
src/components/TradeForm/index.js
src/components/index.js
src/containers/OptionContainer/index.jsx
src/containers/index.js
src/pages/index.jsx

- [Feat | OptionContainer 생성 및 관련 Form 추가](https://github.com/beomgye/where-is-my-hometown/commit/5554bfb03c10329854180b0a7e4f79c606c27071)

Feat | OptionContainer 생성 및 관련 Form 추가

---

.eslintrc.json

- [Fix | import/no-extraneous-dependencies 오류 해결](https://github.com/beomgye/where-is-my-hometown/commit/cd1bb05f5b2434262ab77af8cc83da343cd63107)

Fix | import/no-extraneous-dependencies 오류 해결

---

src/components/common/Button/index.jsx
src/components/common/Form/index.jsx

- [Feat | Form 컴포넌트 레이아웃 제작](https://github.com/beomgye/where-is-my-hometown/commit/7c66ba55bc96dc0a33e396ea8288319c15c2ba11)
- [Refactor | Button type 옵션으로 변경](https://github.com/beomgye/where-is-my-hometown/commit/311c43316d48b7030939e19ee09137d78c8d9e42)
버튼 타입 옵션으로 변경

Feat | Form 컴포넌트 레이아웃 제작

---

src/components/common/Input/index.jsx
src/components/index.js

- [Feat | Input 컴포넌트 제작](https://github.com/beomgye/where-is-my-hometown/commit/74e5a5937520f11aaf8e45d4cc4c0bb9e36ace49)

Feat | Input 컴포넌트 제작

---

src/components/common/Form/index.jsx

- [Feat | Form 컴포넌트 레이아웃 제작 (2)](https://github.com/beomgye/where-is-my-hometown/commit/4b491b2c2b50a4e2dc87b6f22d5ee77760a7006a)
기본 폼 레이아웃

Feat | Form 컴포넌트 레이아웃 제작 (2)

---

src/pages/_document.jsx
src/pages/index.jsx

- [Design | RootLayout 수정](https://github.com/beomgye/where-is-my-hometown/commit/76bcd9381ca5e378bd9d5e625165c19db87bf285)
- 중앙정렬 구현

Design | RootLayout 수정

---

src/components/NavBar/index.jsx

Feat | NavBar 마크업 완성

---

.eslintrc.json
.prettierrc

- 가독성을 위해 세미콜론 사용
- [Fix | 세미콜론 규칙 추가](https://github.com/beomgye/where-is-my-hometown/commit/fa1e647c9852df9189d7a25ec454d007fd6489e4)
가독성을 위해 세미콜론 사용, 이에 규칙 수정

Fix | 세미콜론 규칙 추가

---

src/components/AssetInputForm/index.js
src/components/AssetInputForm/index.jsx
src/components/LocationForm/index.js
src/components/LocationForm/index.jsx
src/components/TradeForm/index.js
src/components/TradeForm/index.jsx
src/components/index.js
src/containers/OptionContainer/index.jsx

- [Feat | OptionContainer step 을 통한 옵션 선택창 변경 구현](https://github.com/beomgye/where-is-my-hometown/commit/08c2d3fce1efae3b47d26a84d396c102daa433d1)
- [Feat | AssetInput, Location, Trade 폼 기본 레이아웃 제작](https://github.com/beomgye/where-is-my-hometown/commit/6c746a47d1ff5dc8381f22827273bd764bf6be8b)

Feat | AssetInput, Location, Trade 폼 기본 레이아웃 제작

---

src/components/common/NavBar/index.jsx

Refactor | NavBar 컴포넌트 레이아웃 수정 #8

---

src/components/common/Form/index.jsx
src/components/common/NavBar/index.jsx
src/containers/OptionContainer/index.jsx
src/pages/_document.jsx
src/pages/index.jsx

- [Design | Form NavBar 추가, CSS 설정](https://github.com/beomgye/where-is-my-hometown/commit/50173ba41b380e5a4d2724b46a559f1d7e01b2e2)

Design | Form NavBar 추가, CSS 설정

---

src/components/common/Form/index.jsx

- [Feat | 뒤로가기 버튼 기능 구현](https://github.com/beomgye/where-is-my-hometown/commit/c64d6cc5784431b77c2c275cc58351a22a634588)

Feat | 뒤로가기 버튼 기능 구현

---

src/components/BuildingTypeForm/index.js
src/components/BuildingTypeForm/index.jsx
src/components/FinishForm/index.js
src/components/FinishForm/index.jsx
src/components/TradeForm/index.jsx
src/components/common/Header/index.jsx

- [Feat | 파일명 변경 및 Form 기본 레이아웃 추가](https://github.com/beomgye/where-is-my-hometown/commit/1212d4a4cf6787bace221e779e22bb582fd7c028)

Feat | 파일명 변경 및 Form 기본 레이아웃 추가

---

src/components/BuildingTypeForm/index.jsx
src/components/TradeForm/index.jsx
src/components/common/Checkbox/index.jsx
src/types/plan.js

- checkbox on/off 가 반대로 되어 이를 해결하고자 리팩토링 진행

[Refactor] Checkbox 관련 문제 발생으로 인한 리팩토링

---

src/components/FinishForm/index.jsx

Feat | Finish Form 레이아웃 완성 #34

---

src/components/FinishForm/index.jsx

- FInishForm input range 삭제 및 레이아웃 수정

Refactor | FInishForm input range 삭제 및 레이아웃 수정 #34

---

src/components/Address/index.jsx
src/components/BuildingTypeForm/index.jsx
src/components/FinishForm/index.jsx
src/components/LocationForm/index.jsx
src/components/common/Form/index.jsx
src/components/common/InputField/index.jsx
src/containers/OptionContainer/index.jsx

- FinishForm 요약 기능 구현 (option으로 상태 관리)
- LocationForm 에서 위치값 option에 저장 구현

[Feat] FinishForm 요약 기능 구현

---

src/components/Address/index.jsx
src/components/LocationForm/index.jsx
src/containers/OptionContainer/index.jsx

Address(하위컴포넌트)에 있는 address value 값을 상위 컴포넌트인 OptionContainer에 전달 후 Location-form 에 전달해주었습니다
form에 bcode 값이 들어가구 address 값도 입력 시 전 단계로 돌아가도 값이 남아있습니다.

[Feat] Address 불필요한 State 삭제 및 location Form연결 

---

src/components/SelectInfo/index.jsx
src/components/index.js
src/containers/OptionContainer/index.jsx

- 정보 선택 레이아웃 완성
- 초기화 버튼 만들기
Feat | SelectInfo 레이아웃 완성 #47

Feat | SelectInfo 레이아웃 완성

---

src/components/common/Form/index.jsx

- [Refactor | Form Footer 레이아웃 변경](https://github.com/beomgye/where-is-my-hometown/commit/74d8d36085c6073c3dc884a3274bacf03bdb89c6)

Refactor | Form Footer 레이아웃 변경

---

src/components/BuildingTypeForm/index.jsx
src/components/TradeForm/index.jsx
src/components/common/Container/index.jsx
src/components/index.js

TradeTypeForm 과 BuildingTypeForm 에 사용되는 Container를 제작 및 리팩토링

[Feat] Container 컴포넌트 제작

---

public/icons/checkbox-checked.svg
public/icons/checkbox-unchecked.svg
src/components/common/Checkbox/index.jsx

- [Refactor | Checkbox 로고 변경](https://github.com/beomgye/where-is-my-hometown/commit/86c4d92821726843ce4a8e358589cb75b853341a)

[Refactor] Checkbox 로고 변경

---

src/components/AssetInputForm/index.jsx
src/components/common/InputField/index.jsx

- React.forwardRef() 로 해결
- [Fix | react-hook-form ref 오류 해결](https://github.com/beomgye/where-is-my-hometown/commit/f44140e81896776193690204cc41b3637a997db0)

[Fix] react-hook-form ref 오류 해결

---

src/components/common/Checkbox/index.jsx

- [Fix | Checkbox react-hook-form ref 오류 해결](https://github.com/beomgye/where-is-my-hometown/commit/4363dec929c219c3ed53b0c240a4c4116b8e734c)

[Fix] Checkbox react-hook-form ref 오류 해결

---

public/icons/vector.svg
src/components/index.js
src/components/screens/SplashScreen/index.jsx
src/pages/index.jsx

- [Feat | SplashScreen 컴포넌트 제작 및 구현](https://github.com/beomgye/where-is-my-hometown/commit/5cba0cd41288c57c5b4c920d28a01ecb61840e34)

[Feat] SplashScreen 컴포넌트 제작 및 구현

---

src/components/common/InputField/index.jsx
src/components/screens/FinishForm/index.jsx
src/containers/OptionContainer/index.jsx

- 원본 저장, 화면에 렌더링은 formatMoney 로 출력

[Refactor] Assets 입력값 저장 방식 변경

---

package-lock.json
package.json
src/api/axiosInstance.js
src/containers/OptionContainer/index.jsx

- cors 에러 발생으로 실제 구현 X
- [Feat | axios 세팅 및 fetch 구현](https://github.com/beomgye/where-is-my-hometown/commit/fdad5f496d3c921e665fbc90ad4b6421ffee91e9)

[Feat] axios 세팅 및 fetch 구현

---

src/pages/_document.jsx

- 초기 페이지 렌더링시 CSS가 일시적으로 적용되지 않다가 후에 적용되는 문제가 발생되어 (FOUC 문제) 이를 방지하고자 수정한 작업
- [Fix | 초기 페이지 렌더링시 FOUC 문제 해결](https://github.com/beomgye/where-is-my-hometown/commit/35f43512b3fa65780c6cd33e95e0caa5e28396d8)

Fix | 초기 페이지 렌더링시 FOUC 문제 해결

---

src/components/screens/FinishForm/index.jsx

- 거래방식, 건물유형 출력값 수정 및 스타일 수정 #34

Refactor | 거래방식, 건물유형 출력값 수정 및 스타일 수정 #34

---

src/components/common/NavBar/index.jsx
src/components/screens/SplashScreen/index.jsx

Refactor | navbar, splashscreen CSS 수정

---

next.config.js
package-lock.json
package.json
src/components/common/Loading/index.jsx
src/components/index.js
src/containers/OptionContainer/index.jsx
src/hooks/useFindMyHome.jsx

- 데이터 페칭 과정에서 사용할 loading 컴포넌트 제작

[Feat] Loading 컴포넌트 제작

---

src/components/screens/SelectInfo/index.jsx
src/components/screens/SummaryForm/index.jsx

- SelectInfo, SummaryForm CSS 수정

Feat | SelectInfo, SummaryForm CSS 수정

---

src/components/common/NavBar/index.jsx
src/components/common/Radio/index.jsx
src/components/screens/AssetInputForm/index.jsx
src/components/screens/BuildingTypeForm/index.jsx
src/components/screens/LocationForm/index.jsx
src/components/screens/SummaryForm/index.jsx
src/components/screens/TransactionTypeForm/index.jsx
src/constants/index.js
src/containers/OptionContainer/index.jsx
src/hooks/useFindMyHome.jsx

- constants 변경으로 인한 리팩토링 관련 PR

[Refactor] constants 데이터 변수 리팩토링

---

.github/workflows/deploy.yml

- [Feat | workflow 환경변수 설정 추가 (.env)](https://github.com/beomgye/where-is-my-hometown/commit/01fa5ffd23c6327aba62d21281a22095c3214f14)

Feat | workflow 환경변수 설정 추가 (.env)

---

.github/workflows/deploy.yml

- [Refactor | deploy 관련 워크플로우 재구성](https://github.com/beomgye/where-is-my-hometown/commit/a19a054d6c2e51f62b2785ce95f8081f2dea1949)

Refactor | deploy 관련 워크플로우 재구성

---

.github/workflows/deploy.yml

Refactor | deploy node-version 수정

---

.github/workflows/deploy.yml

Refactor | deploy node 관련 수정

---

.github/workflows/deploy.yml

Refactor | deploy aws s3 sync 수정

---

src/MultiFormContainer/index.tsx
src/types/form.d.ts

- 타입 분리를 위한 form.d.ts 생성 (MultiFormProps)

[Refactor] 타입 분리를 위한 form.d.ts 생성 (MultiFormProps)

---

src/components/common/Address/index.tsx
src/components/screens/LocationForm/index.tsx

Refactor | Type지정 및 타입 > 스타일 > 코드 순으로 바꾸기

---

src/MultiFormContainer/index.tsx
src/components/common/Form/index.tsx
src/components/screens/AssetInputForm/index.tsx
src/components/screens/BuildingTypeForm/index.tsx
src/components/screens/LocationForm/index.tsx
src/components/screens/SplashScreen/index.tsx
src/components/screens/SummaryForm/index.tsx
src/components/screens/TransactionTypeForm/index.tsx
src/hooks/useFindMyHome.tsx
src/pages/_document.tsx
src/pages/index.tsx

- [Refactor | FormProps 타입 변경 및 Form 파일 내 컴포넌트 절대경로 수정](https://github.com/beomgye/where-is-my-hometown/commit/31333293f8bda2ed985e7d618f91709ae11163fe)
- [Refactor | useFindMyHome location 제거](https://github.com/beomgye/where-is-my-hometown/commit/4f5b8cb0f4e1d783bec06ffdafd33d94abbcc932)
- [Refactor | 기본 시스템 파일 내 절대경로 수정 및 코드 구성 변경](https://github.com/beomgye/where-is-my-hometown/commit/fbf74c79dd8cdce617e0069c8bcf4ff0ec2b9cad)
- [Refactor | MultiFormContainer 절대경로 수정 및 불필요한 코드 제거](https://github.com/beomgye/where-is-my-hometown/commit/51ab8fc284d83cd7cf2ee123f8eeeabe2f97eb0b)
- [Fix | TS 전환 이후 Button 컴포넌트 오류 발생으로 인한 문제 해결](https://github.com/beomgye/where-is-my-hometown/commit/f3b15accdb0a8078d874eff94128bc13b324259a)
- [Refactor | SplashScreen 코드 구조 …

[Fix] TS 전환 이후 MultiFormContainer 관련 오류 해결

---

README.md

- TypeScript 리팩토링 관련 README 수정

[Docs] TypeScript 리팩토링 관련 README 수정
